- name: Configurar acceso a EKS con kubectl
  hosts: all
  become: yes

  vars:
    region: us-east-1
    cluster_name: dev-eks-cluster

  tasks:
    - name: Instalar awscli y kubectl
      package:
        name: "{{ item }}"
        state: present
      loop:
        - awscli
        - kubectl

    - name: Configurar kubeconfig para EKS
      shell: >
        aws eks update-kubeconfig --region {{ region }} --name {{ cluster_name }}
      environment:
        AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
      register: kubeconfig_output

    - name: Mostrar salida de configuración
      debug:
        var: kubeconfig_output.stdout